### ISSUE TITLE
Top Artist list bugged

### ISSUE THREAD

**Issue by Blackkite-Development** [MrKrisKrisu/KStats#124]
The lists for Top Artists (Last 7 days, last 30 days and all time) seems get some kind of wrong data, since only shows one artist I never listend but people I follow/who are in my spotify plan. 
![2021-08-23 22_41_56-Window](https://user-images.githubusercontent.com/72868713/130516635-59f777a6-9e9d-4995-ae2d-e688883e2154.png)

**Comment by Blackkite-Development** [comment]
It also shows a random "favorite year" it seems since I personally haven't listend to any music from this time.

**Comment by MrKrisKrisu** [comment]
Thanks for the report! Unfortunately, I had overlooked that during the last database migration.
