### ISSUE TITLE
Kstats Bot broken and can't connect

### ISSUE THREAD

**Issue by rophl** [MrKrisKrisu/KStats#126]
The Kstats Bot is sending me the same message over and over again every minute and I can't connect as the "/connect CODE" (or any input on my side) gets ignored.

![image](https://user-images.githubusercontent.com/90791070/133480402-b2647f2a-dee5-48bb-835a-aa068ac09ab5.png)

**Comment by MrKrisKrisu** [comment]
Sorry for the trouble! The bot should work again now.
