### ISSUE TITLE
Spotify "Listened minutes" times wrong

### ISSUE THREAD

**Issue by jameskitt616** [MrKrisKrisu/KStats#127]
I usually listen 10-12 hours music a day for the past months and recently KStats shows wrong statistics.
I noticed it because last 7/30 days shows completely wrong numbers, for the 7 day stats it should show somthing around 4000-6000 minutes.

![image](https://user-images.githubusercontent.com/52933658/135222959-98ec27d5-94c1-4879-9f3e-7d5d35630c72.png)

**Comment by MrKrisKrisu** [comment]
Thanks for reporting!

**Comment by jameskitt616** [comment]
same thing, seems to be broken again.
![image](https://user-images.githubusercontent.com/52933658/141309175-ff2f1003-7825-4cf3-8523-fcad4b79cc16.png)

**Comment by MrKrisKrisu** [comment]
I have just checked this again. The data is counted correctly for me.

https://github.com/MrKrisKrisu/KStats/blob/c9f5d52554277e7b2a8f1b467e9d4c2efda20fd4/app/Http/Controllers/SpotifyController.php#L392

**Comment by jameskitt616** [comment]
Two days later, the listen time just goes more down. (My account is still connected, i still get song history etc.)

![image](https://user-images.githubusercontent.com/52933658/141649682-498b391a-7835-449a-938c-b81789662ad8.png)
