### ISSUE TITLE
Problem with adding new mail address for Rewe Ebon

### ISSUE THREAD

**Issue by lukaslgz** [MrKrisKrisu/KStats#63]
It is not possible to assign a new email address.
When adding a new email address you will be redirected to https://k118.de/settings/add_mail and there you will get the error 500 | Server Error. 

When going back to the settings, the new address is entered, but as "unverified". There will be no mail sent to confirm the mail. 

I tried it with two different mails from two different providers. @gmx.de and @gmail.com

I also tried two different browsers.
Firefox 69.0.3 (32-bit)
Google Chrome 58.0.4183.102 (64-bit)

**Comment by MrKrisKrisu** [comment]
Thanks for reporting! :) 
This were old credentials for sending verification mails in the .env configuration. I've fixed that at the current installation. You should now get the mail without any error.

I will create a understandable alert message for this case soon.

**Comment by lukaslgz** [comment]
perfect it works. Thanks for the quick fix
