### ISSUE TITLE
Telegram Connect Problems with linking

### ISSUE THREAD

**Issue by lukaslgz** [MrKrisKrisu/KStats#64]
I have tried to link my account with Telegram Connect. 
Therefore I have added the account kstats via the link and then sent /start and /connect [code].

After nothing happened, I generated a new code and tried again. Unfortunately without success.

Error on Telegram Android 7.0.1

![Screenshot_20200916-142126~2](https://user-images.githubusercontent.com/71385455/93336808-8c08f900-f828-11ea-9312-b2d0cecd42a2.png)

**Comment by MrKrisKrisu** [comment]
Thanks for reporting! I can confirm that the Bot doesn't respond.
I will have a look at this soon.
