### ISSUE TITLE
Improvement suggestion for the ReweBon Crowdsourcing

### ISSUE THREAD

**Issue by lukaslgz** [MrKrisKrisu/KStats#65]
I used the Crowdsoursing function in the Rewe Bon function and I think it is very good. 
Especially the vergetarian tasks on the right side are great.

However, I have a suggestion for improvement for the product categories. 
I think it is great that there are so many different and detailed categories. But unfortunately it makes it very difficult to find the right category in the current list. I find it very frustrating if you don't know the right top category to find the right item.

I have a small suggestion for improvement.
Split the two current terms connected with an arrow into two different fields. A top category which you define first and then a subcategory which will be filtered and displayed according to the top category. 
This also makes later evaluation in the statistics easier.

Alternatively, a full text search for the right categories would make the input much easier.

Only a small suggestion from my side. I hope I could help you. 
I find your project very nice.

Best regards 
Lukas

**Comment by MrKrisKrisu** [comment]
Thanks for your suggestions! I will add a full text search for this. I think this is the easiest way to implement this soon.
